name: Analyse quality
on:
  push:
    branches:
      - master
    paths:
      - .github/workflow/**
      - sonar-project.properties
      - apps/**
      - libs/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflow/**
      - sonar-project.properties
      - apps/**
      - libs/**

jobs:
  analyse:
    name: Analyse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}