name: Deploy Alexa skills
on:
  push:
    branches:
      - master
      - issue/36-write-document-to-update-alexa-skill
    paths:
      - .github/workflows/deploy-skills.yml
      - libs/lib-common/src/assets/amazon-alexa-skills/skills.json

concurrency:
  group: deploy-skills
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ASK_VENDOR_ID: ${{ secrets.ASK_VENDOR_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SKILL_ID: ${{ secrets.SKILL_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Install ASK cli
        run: |
          npm install --global ask-cli@2.27.0

      - name: Update Skill Model
        run: ask smapi set-interaction-model -s ${{ secrets.SKILL_ID }} -l fr-FR --interaction-model file:libs/lib-common/src/assets/amazon-alexa-skills/skills.json

      - name: Check Skill Status
        run: |
          status="IN_PROGRESS"
          i=0
          while [ "$status" != "SUCCEEDED" ]; do
            ask smapi get-skill-status --skill-id ${{ secrets.SKILL_ID }} --resource interactionModel > status.json
            status=$(node -e "console.log(require('./status.json').interactionModel['fr-FR'].lastUpdateRequest.status)")
            sleep 60
            ((i=i+1))
            if [ $i -gt 300 ]; then
              echo "❌ UNABLE TO CHECK THE SUCCESS OF THE DEPLOYMENT ❌"
              exit 1
            fi
          done
          echo "✅ SUCCESS ✅"
