name: Deploy skills
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # - name: Alexa ASK AWS CLI Action
      #   uses: xavidop/alexa-ask-aws-cli-docker@v1.0.6