name: Publish installers
on:
  push:
    branches:
      - master
jobs:
  retrieve_information:
    name: Retrieve information
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Write file
        run: |
          echo $(node -e "console.log(require('./package.json').name)") > name.txt
          echo $(node -e "console.log(require('./package.json').version)") > version.txt
          touch app.AppImage
          echo "APP_NAME=$(cat name.txt)" >> $GITHUB_ENV
          echo "APP_VERSION=$(cat version.txt)" >> $GITHUB_ENV
          echo $GITHUB_ENV

      - name: Echo
        run: |
          echo $GITHUB_ENV
          echo ${{env.APP_NAME}}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: information
          path: |
            name.txt
            version.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: app.AppImage

  # build_linux_installer:
  #   name: Build Linux installer
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.15.0'

  #     - name: Build
  #       run: |
  #         npm install
  #         npm run postinstall
  #         npm run publish:linux

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: linux
  #         path: dist/executables/app.AppImage

  # publish_window_installer:
  #   name: Publish Windows installer
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.15.0'

  #     - name: Build
  #       run: |
  #         npm install
  #         npm run postinstall
  #         npm run publish:windows

  #     - name: Save
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: windows
  #         path: dist/executables/app.exe

  # publish_macos_installer:
  # name: Publish macOS installer
  # runs-on: macos-latest
  # steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Setup Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '16.15.0'

  #   - name: Build
  #     run: |
  #       npm install
  #       npm run postinstall
  #       npm run publish:macos

  #   - name: Save
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: macos
  #       path: dist/executables/app.dmg

  release:
    name: Release
    needs: [retrieve_information]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Set GITHUB_ENV
        run: |
          ls information
          cat information/name.txt
          cat information/version.txt
          echo "APP_NAME=$(cat information/name.txt)" >> $GITHUB_ENV
          echo "APP_VERSION=$(cat information/version.txt)" >> $GITHUB_ENV

      - name: Prepare files
        run: |
          cat $GITHUB_ENV
          echo ${{env.APP_NAME}}
          echo ${{env.APP_VERSION}}
          cp linux/app.AppImage linux/${{env.APP_NAME}}-latest.AppImage         
          mv linux/app.AppImage linux/${{env.APP_NAME}}-${{env.APP_VERSION}}.AppImage

      - name: Update latest version release
        uses: meeDamian/github-release@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{env.APP_VERSION}}
          name: Open days with Alexa [${{env.APP_VERSION}}]
          files: >
            linux/${{env.APP_NAME}}-${{env.APP_VERSION}}.AppImage
          allow_override: true
      
      - name: Update latest version release
        uses: meeDamian/github-release@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          name: Open days with Alexa [latest]
          files: >
            linux/${{env.APP_NAME}}-latest.AppImage
          allow_override: true
