name: Publish installers
on:
  push:
    branches:
      - master
jobs:
  # publish_window_installer:
  #   name: Publish Windows installer
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.15.0'

  #     - name: Build
  #       run: |
  #         npm install
  #         npm run postinstall
  #         npm run publish:windows
    
  #     - name: Save
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: open-days-with-alexa-latest.exe
  #         path: dist/executables/open-days-with-alexa-latest.exe

  # publish_macos_installer:
    # name: Publish macOS installer
    # runs-on: macos-latest
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2

    #   - name: Setup Node.js
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: '16.15.0'

    #   - name: Build
    #     run: |
    #       npm install
    #       npm run postinstall
    #       npm run publish:macos
      
    #   - name: Save
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: open-days-with-alexa-latest.dmg
    #       path: dist/executables/open-days-with-alexa-latest.dmg

  build_linux_installer:
    name: Build Linux installer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Build
        run: |
          npm install
          npm run postinstall
          npm run publish:linux
      
      - name: Save
        uses: actions/upload-artifact@v3
        with:
          name: open-days-with-alexa-latest.AppImage
          path: dist/executables/open-days-with-alexa-latest.AppImage
  
  release:
    name: Release
    needs: [build_linux_installer]
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Linux installer
        uses: actions/download-artifact@v3
        with:
          name: open-days-with-alexa-latest.AppImage
          path: ~/open-days-with-alexa-latest.AppImage

      - name: Update latest version release
        uses: meeDamian/github-release@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          name: Open days with Alexa [latest]
          files: >
            open-days-with-alexa-latest.AppImage
          allow_override: true
    