name: Publish installers
on:
  push:
    tags:
      - 'latest'
jobs:
  publish_window_installer:
    name: Publish Windows installer
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Build
        run: |
          npm install
          npm run postinstall
          npm run publish:windows
    
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: open-days-with-alexa-windows-latest
          path: dist/executables/*.exe*

  publish_macos_installer:
    name: Publish macOS installer
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Build
        run: |
          npm install
          npm run postinstall
          npm run publish:macos
    
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: open-days-with-alexa-macos-latest
          path: dist/executables/*

  publish_linux_installer:
    name: Publish Linux installer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Build
        run: |
          npm install
          npm run postinstall
          npm run publish:linux
    
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: open-days-with-alexa-linux-latest
          path: dist/executables/*
